Unit tests do not fail if a ConcurrentMergeScheduler thread hits an exception
Now that CMS is the default it s important to fail any unit test that hits an exception in a CMS thread. But they do not fail now. The preferred solution thanks to Erik Hatcher is to fix all Lucene unit tests to subclass from a new LuceneTestCase in o.a.l.util base that asserts that there were no such exceptions during the test. Attached patch. Note that whenever we add a new Lucene unit test you must subclass from LuceneTestCase and take care to call super.setUp in setUp and super.tearDown in tearDown if you override these methods. I just committed this. Please make sure any newly added unit tests for Lucene subclass from LuceneTestCase 
