Some Lucene tests try and use a Junit Assert in new threads
There are a few cases in Lucene tests where JUnit Asserts are used inside a new threads run method - this won t work because Junit throws an exception when a call to Assert fails - that will kill the thread but the exception will not propagate to JUnit - so unless a failure is caused later from the thread termination the Asserts are invalid. TestThreadSafe TestStressIndexing2 TestStringIntern Chris Male mentioned to me that he thinks Uwe has fixed this This is fixed But some of the threads use a own exception handler calling ex.printStackTrace and so those bugs are not detected. But all asserts in foreign threads are fine now so unless a failure is caused later from the thread termination the Asserts are invalid This is one small problem The exceptions from external threads are collected on tearDown . So the assert message is only printed and the test failing in tearDown . So this does not prevent failures in the main thread before the failures in other thread s assert statements are detected. But one is sure The failures are detected and the test is failing. Duplicate of LUCENE-2274.
