Not getting random-seed reproduce-with if a test fails from another thread
See https builds.apache.org job Lucene-Solr-tests-only-trunk 12822 console as an example. This is at least affecting 4.0 maybe 3.x too A good example of this is to un- Ignore TestKuromojiTokenizer.testRandomHugeStrings LUCENE-3897 in modules analysis kuromoji it fails from another thread but there is no seed. Here s a really hackish solution. Hopefully Dawid hates it and knows of a way to fix it cleanly Thanks Robert. I m trying this in order to reproduce a failing case for LUCENE-3897. This does the job very well and I can reproduce a case now. Thanks Hopefully Dawid hates it and knows of a way to fix it cleanly It s fine for the trunk. It will be redundant in LUCENE-3808 the seed is reported at master build level there exceptions have an injected fake stack trace entry with the current master test seed combination even though the test seed is redundant most of the time because it s derived . Added a JUnit test to verify test seed is printed. Feel free to commit in 4.0 3.x Robert. Thanks Dawid and also for the cool test . I ll commit soon. I committed the fix. Dawid has a cleaner solution the new runner long-term.
